# Generated by Django 4.1.3 on 2023-01-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('head0', models.CharField(max_length=100)),
                ('head0content', models.CharField(max_length=5000)),
                ('head1', models.CharField(max_length=100)),
                ('head1content', models.CharField(max_length=5000)),
                ('head2', models.CharField(max_length=100)),
                ('head2content', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
