# Generated by Django 4.1.3 on 2022-11-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shhop', '0003_contact_alter_product_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='pub_date',
            new_name='date',
        ),
    ]
