# Generated by Django 4.1.3 on 2022-12-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shhop', '0006_alter_order_date_of_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_order',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
