# Generated by Django 4.1.3 on 2022-12-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shhop', '0008_alter_order_date_of_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('orderid', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
